version: '3.5'

services:
  office-app:
    build:
      context: '.'
      args:
        uid: 1000
    container_name: office-app
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    networks:
      backend:
        aliases:
          - office-app

  mysql-db-office:
    image: mysql:5.7
    container_name: mysql-db-office
    restart: always
    volumes:
      - ./run/var:/var/lib/mysql
      - ./run/init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=office
      - MYSQL_USER=office
      - MYSQL_PASSWORD=office
    command: --init-file /data/application/init.sql
    networks:
      backend:
        aliases:
          - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - mysql-db-office:db
    ports:
        - 8765:80
    environment:
        MYSQL_ROOT_PASSWORD: securerootpassword
        PMA_HOST: db
    depends_on:
        - mysql-db-office
    networks:
      backend:
        aliases:
          - pma

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      backend:
        aliases:
          - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      backend:
        aliases:
          - mongo-express

networks:
  backend:
    name: backend-network